### ISSUE TITLE
missing array

### ISSUE THREAD

**Issue by alexbujenita** [learn-co-curriculum/fewpjs-iterators-reduce#4]
> Create a new variable called totalBatteries which is the sum of all of the battery amounts in the batteryBatches array. Naturally, use reduce() for this!

batteryBatches is missing

**Comment by drakeltheryuujin** [comment]
Hi @alexbujenita,
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
