### ISSUE TITLE
Missing content

### ISSUE THREAD

**Issue by NickyEXE** [learn-co-curriculum/fewpjs-iterators-reduce#6]
We're not given a battery batches array to write a function on.

**Comment by drakeltheryuujin** [comment]
Hi @NickyEXE ,
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
